### PR TITLE
Add azure build pipeline

### PR DESCRIPTION
**Pull request by markgibbons25**
Hi @richardszalay and @muso31, just thought I'd open this PR, please can you give it a test and let me know any changes. It uses the logic described here https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2

### CODE REVIEW

**Comment by richardszalay** [comment]
Nice work, Mark! Does that artifact publish automatically pick up the WDP that was generated?

Overall I think it's a good foundation and could possibly be merged as-is. Moving forward, we should run unit tests and maybe even capture the coverage data.

**Comment by richardszalay** [comment]
Also, we should update the `rename.ps1` script so that it replaces the project reference in azure-pipelines.yml. I'd say it's worth prioritising that before we merge, otherwise it will only cause problems.

**Comment by muso31** [comment]
@richardszalay the rename.ps1 script (from @josefprice) will recursively replace any 'Helixbase' references in .yml files so I think this is covered? https://github.com/muso31/Helixbase/blob/master/tools/rename.ps1#L51 

Great work @markgibbons25

**Comment by richardszalay** [comment]
@muso31 ah yes right you are.

**Comment by markgibbons25** [comment]
Added the artifact directory and double checked that everything works in azure devops.

**Comment by richardszalay** [comment]
Fantastic. Looks good to me!

**Pull request merged**
