### PR TITLE
Introduces an example build script

### PR DESCRIPTION
**Pull request by steviemcg**
- Builds and unit tests the solution
- Installs Sitecore and its prerequisites if necessary
- Deploys the solution with Helix Publishing Pipeline
- Saves developer settings under /App_Config/Environment/
- Syncs the Unicorn serialized items to Sitecore
- Executes a Smart Publish
- Rebuilds the Link Databases
- Rebuilds the Search Indexes
- Deploys the Marketing Definitions
- Packages the files and items to separate artifacts (again using HPP)

Compatible with AppVeyor (see appveyor.yml)

### CODE REVIEW

**Comment by steviemcg** [comment]
See example log from https://ci.appveyor.com/project/steviemcg/helixbase/builds/25432136

**Comment by richardszalay** [comment]
This looks great, but tbh it introduces a _lot_ and delves into deployment territory which I'm not sure we should be opinionated about.

Perhaps it should be moved into `build/examples/appveyor` or something to show that it's an example?

**Comment by steviemcg** [comment]
It’s not specific to AppVeyor as it can also be run locally, on TeamCity, Azure Pipelines, etc.

I’m sure you’re right, but can you give more reasons / examples? My feeling is that this entire repository is an opinionated example, why is an example build script any different? Shouldn’t we strive to introduce conventions and good practices there too?

**Comment by richardszalay** [comment]
That's a fair point. Let look at what you've done in more detail.

**Pull request closed without merging**
