### PR TITLE
Feature/sc91

### PR DESCRIPTION
**Pull request by piratebriggs**
Hi,

I've recently upgraded a project based on HelixBase to sitecore 9.1 and found it was more work than I was expecting! I thought I'd save other people the bother and contribute back.

In essence this branch replaces the packages.config with PackageReference, upgrades the Sitecore.* packages from the 9.1 feed and fixes the resulting indirect reference fallout.

I've only tested this as far as getting it to compile - however I completed the same steps on my own solution and it does deploy and run so I'm pretty confident of the work.

It looks like a monster PR so I've not squashed the steps taken to get here.

### CODE REVIEW

**Comment by piratebriggs** [comment]
Oooh, fogot to mention - the reason for replacing packages.config is that Sitecore are no longer releasing NoReferences versions of their packages. There's some reading here https://www.waitingimpatiently.com/package-reference-nuget/

**Comment by muso31** [comment]
@piratebriggs this looks great thanks for your hard work. I'll get this in asap, just need to check Glass etc as I don't think it's compatible with 9.1 just yet

**Comment by piratebriggs** [comment]
Good point, we're not using Glass in our own solution yet.

**Comment by muso31** [comment]
@piratebriggs Glass has been updated now so I'll get this merged in very soon

**Pull request merged**
